### ISSUE TITLE
NoMethodError: undefined method `original_id' for nil:NilClass

### ISSUE THREAD

**Issue by fuji-nakahara** [fuji-nakahara/genron-sf-app#3]
https://sentry.io/genron-sf/genron-sf/issues/614037987/

```
NoMethodError: undefined method `original_id' for nil:NilClass
  config/routes.rb:25:in `block (2 levels) in <main>'
    "http://school.genron.co.jp/works/sf/#{work.subject.term_id}/students/#{work.student.original_id}/#{work.original_id}/"
  app/models/work.rb:23:in `original_url'
    Rails.application.routes.url_helpers.original_work_url(self)
  app/models/work.rb:12:in `update_contents'
    doc         = Nokogiri::HTML(open(original_url))
  app/jobs/scrape_works_job.rb:12:in `block in perform'
    Work.find_or_create_by(subject: subject, student: student, original_id: work_id, &:update_contents)
  app/jobs/scrape_works_job.rb:10:in `each'
    student_id_to_work_id.each do |student_id, work_id|
...
(78 additional frame(s) were not displayed)

NoMethodError: undefined method `original_id' for nil:NilClass
```

**Comment by fuji-nakahara** [comment]
I'll reopen if this error occurred again.
